#!/usr/bin/zsh

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

function run-once {
	pgrep "$1" > /dev/null || $@
}

#run-once kanshi &
run-once fcitx5 > .local/share/qtile/fcitx5.run 2>&1 &
run-once dunst > .local/share/qtile/dunst.run 2>&1 &
run-once keepassxc &
run-once thunderbird > .local/share/qtile/thunderbird.run 2>&1 &

# fucking piece of bullcrap crashes every few seconds
#run-once signal-desktop --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer > .local/share/qtile/signal.run 2>&1 &